@startuml
actor "Пользователь" as u
participant "Frontend" as f
participant "Backend" as b
database "Database" as d
skinparam sequenceMessageAlign center
title Получение списка брендов
autonumber 
u++
u->f++:Зашел на страницу c каталогом брендов
f->b++:Запрос на получение списка имеющихся брендов \n Get rest\api\v1\brendlist
b->d++:Получение данных о брендах \n с признаком активен
alt Успешный ответ
d-->b:Передает данные по брендам \n (id, name, logo_id и т.д.)
b-->f:200 OK с данными по доступным брендам
f-->u:Отображает список брендов на странице
else Ошибка Базы данных
d-->b--: Внутренняя ошибка базы данных
b-->f--:500 Internal server error \n Внутренняя ошибка
f-->u--: Уведомление: "Произошла ошибка сервера.\n Попробуйте обновить страницу"
u--
end
@enduml