@startuml
left to right direction
title Изменения контента в списке брендов

Пользователь--(Перейти к просмотру \n брендов списком)
note top of Пользователь: Контент-менеджер\nРасширен функционал возможностей
(Перейти к просмотру \n брендов списком) -.> (Создать новый бренд)
(Создать новый бренд) -.> (Добавить логотип и указать \n наименование бренду)
(Добавить логотип и указать \n наименование бренду) -.> (Привязать коллекцию \n товаров)
(Привязать коллекцию \n товаров) -.> (Сохранить изменения)
(Сохранить изменения) -.> (Список брендов обновлен)
(Перейти к просмотру \n брендов списком) -.> (Выбрать бренд из списка)
(Выбрать бренд из списка) -.> (Редактировать бренд)
(Редактировать бренд) -.> (Внести изменения \n в карточку бренда)
(Внести изменения \n в карточку бренда) -.> (Привязать коллекцию \n товаров)
(Выбрать бренд из списка) -.> (Удалить существующий бренд)
(Удалить существующий бренд) -.> (Список брендов обновлен)
@enduml