@startuml
left to right direction
rectangle "Переход к товарам бренда" {
actor Пользователь as u
note top of u: Обычный клиент сайта

u -- (Переходит к просмотру \n списка брендов)
(Переходит к просмотру \n списка брендов).> (Поиск бренда по \n наименованию): <<include>>
(Поиск бренда по \n наименованию) -.> (Выбирает бренд из списка): <<extend>>
(Переходит к просмотру \n списка брендов) -.> (Сортирует список \n по наименованию): <<include>>
(Переходит к просмотру \n списка брендов) -.> (Выбирает бренд из списка): <<include>>
(Выбирает бренд из списка) <.- (Сортирует список \n по наименованию): <<extend>>
(Выбирает бренд из списка) -.> (Переходит в каталог \n товаров бренда): <<include>>
}
@enduml