@startuml
title Процесс мульти-продуктовой обработки заявки \n на кредитную карту сервисом адаптером
start
:Поступает заявка по API;
note right
POST /api/v1/order/add
endnote
:Сервис сохраняет заявку в БД с указанием status = CREATED;
:Отправляет API запрос на получение расширенных \n данных по клиенту в CRM-систему; <<output>>
:Получает ответ по данным клиента от API CRM-системы; <<input>>
:Отправляет API запрос в систему рекомендаций \n продуктов для клиента; <<output>>
:Получает ответ по рекомендованным продуктам для клиента  \n от API системы рекомендаций; <<input>>
:Проверяет рекомендованные продукты;
if (Рекомендованы все продукты?) then (Да)
fork
:Запись события в очередь Kafka для процесса (КК);
fork again
:Запись события в очередь Kafka для процесса (ДК);
fork again
:Запись события в очередь Kafka для процесса (КН);
end fork
else (Нет)
If (Рекомендована ДК или КН) then (ДК)
note
Кредитная карта (КК) является
рекомендуемой по умолчанию 
endnote
fork
:Запись события в очередь Kafka для процесса (КК);
fork again
:Запись события в очередь Kafka для процесса (ДК);
end fork
else (КН)
fork
:Запись события в очередь Kafka для процесса (КК);
fork again
:Запись события в очередь Kafka для процесса (КН);
end fork
endif
endif
:Перезаписывает в БД статус заявки с CREATED на SENT;
stop
@enduml