# Тип для описания товара
type Product {
    id: ID!              # Уникальный идентификатор товара
    name: String!        # Наименование товара
    description: String  # Описание товара
    price: Float!        # Цена товара
    bonusPoints: Int!    # Бонусы товара
    quantity: Int!       # Количество товара на складе
    dateCreate: String   # ISO 8601 формат: "2026-01-01T00:00:00Z"
    dateUpdate: String   # ISO 8601 формат: "2026-01-01T00:00:00Z"
}

# Тип для описания ответа при удалении товара
type Response {
    status: Boolean!            # Статус обработки запроса (успех/неудача)
    errorCode: Int              # Код ошибки
    descriptionError: String!   # Описание ошибки при неудачи
}

# Тип для обработки запросов - операций чтения
type Query {
    product(id: ID!): Product                             # Получение товара по идентификатору
    listProducts(limit: Int, offset: Int): [Product!]!    # Получение товара списком, можно задавать лимит/смещение
}

# Тип для обработки мутаций - операций изменения
type Mutation {
    createProduct(idempotenceKey: ID!, name: String!, description: String, price: Float!, bonusPoints: Int!, quantity: Int!):    Product!    # Создание нового товара с ключем идемпотентности для исключения дублей
    updateProduct(id: ID!, name: String!, description: String, price: Float!, bonusPoints: Int!, quantity: Int!): Product!                   # Редактирование товара
    deleteProduct(id: ID!): Response!                                                                                                        # Удаление товара с ответом результата
}

# Точка входа для API
schema {
    query: Query
    mutation: Mutation
}