syntax = "proto3";

package common;

option go_package = "./pk/common";

// Структура для ошибок
message Error {
    string code = 1;                    // Код ошибки
    string message = 2;                 // Сообщение об ошибке
    string fieldName = 3;               // Поле, вызавшее ошибку
    map<string, string> metadata = 4;   //Доп. инфа о ошибке с коллекцией пар ключ-значение
}

// Метаданные ответа
message MetaInfo {
    string requestId = 1;               // ID запроса
    int64 timestamp = 2;                // Время выполнения
    string version = 3;                 // Версия API
    map<string, string> metadata = 4;   //Пара ключ-значение
}

// Пагинация для списков
message Pagination {
    int64 limit = 1;                    // Лимит записей
    int64 offset = 2;                   // Смещение
}

// Общий ответ с статусом и ошибками
message BaseResponse {
    bool status = 1;                    // Успех или неудача
    MetaInfo metaInfo = 2;              // Метаданные
    repeated Error errors = 3;          // Список ошибок
}